[tool.poetry.dependencies]
python = ">=3.11,<3.12"
Flask = "2.3.3"
tensorflow = "2.20.0"
tensorflow-hub = "0.14.0"
numpy = "1.24.3"
soundfile = "0.12.1"
librosa = "0.10.1"
vosk = "0.3.44"
twilio = "8.10.0"

